## Numpy练习

### 1. 创建一个长度为10全为0的一维数组，然后让第5个元素等于1。

In [6]:
import numpy as np

# 创建一个长度为10、全为0的一维数组
x = np.zeros(10)

# 让第5个元素（索引为4）等于1
x[4] = 1

# 打印结果
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 生成一个4X5和一个5X4的矩阵，并计算它们的乘积。

In [5]:
import numpy as np
#创建矩阵A和B
A = np.array([[1,2,3,4],[0,0,0,1],[3,7,8,9],[8,9,0,1],[1,1,1,1]])
B = np.array([[1,2,5,6,0],[5,5,5,5,9],[3,5,1,1,1],[2,2,2,2,2]])
#计算乘积
C = A@B
#输出结果
print(C)

[[28 35 26 27 29]
 [ 2  2  2  2  2]
 [80 99 76 79 89]
 [55 63 87 95 83]
 [11 14 13 14 12]]


### 3. 函数 f 定义如下，其中x是任意实数: 𝑓(𝑥)=(sin⁡(𝑥+1)/𝑒^𝑥 )(𝑥+1)/2，生成一个数组a∈𝑅^5，计算b = f(a)。

In [10]:
import numpy as np
#函数表达式
f = (np.sin(x+1)/np.exp(x))*(x+1)/2
#生成数组a并附赋值给x
a = np.array([0,-1,1,np.pi,-np.pi])
x = a
#计算结果
b = f
#输出结果
print(b)

[0.42073549 0.42073549 0.42073549 0.42073549 0.33451183 0.42073549
 0.42073549 0.42073549 0.42073549 0.42073549]


### 4. 随机生成一个5行10列的矩阵，然后每行元素减去该行的平均值

In [13]:
import numpy as np
#随机生成一个5x10的矩阵
A = np.random.randint(0,100,size=(5,10))
#计算每一行的平均值
B = A.mean(axis=1,keepdims=True)
#计算结果
C = A - B
#输出结果
print(C)


[[ 44.4   7.4 -20.6  -1.6  23.4 -40.6 -32.6  34.4  24.4 -38.6]
 [  7.8  -5.2 -23.2 -27.2   1.8  -4.2  43.8 -27.2  55.8 -22.2]
 [-10.1  -2.1 -33.1  16.9 -42.1  15.9   7.9  -0.1  15.9  30.9]
 [-27.2  12.8   0.8  18.8 -13.2 -38.2   4.8  29.8 -14.2  25.8]
 [-46.4  14.6  38.6  30.6 -47.4 -13.4  41.6 -33.4 -14.4  29.6]]
