In [1]:
# NumPy
import numpy as np
a_np = np.array([1, 2, 3])
print("NP 标量加：", a_np + 5)   # 标量5广播为[5,5,5]
print("NP 标量乘：", a_np * 2)   # 标量2广播为[2,2,2]
print("NP 标量减：", a_np - 1)   # 标量1广播为[1,1,1]

# PyTorch
import torch
a_t = torch.tensor([1, 2, 3])
print("Torch 标量加：", a_t + 5)
print("Torch 标量乘：", a_t * 2)
print("Torch 标量减：", a_t - 1)


NP 标量加： [6 7 8]
NP 标量乘： [2 4 6]
NP 标量减： [0 1 2]
Torch 标量加： tensor([6, 7, 8])
Torch 标量乘： tensor([2, 4, 6])
Torch 标量减： tensor([0, 1, 2])


In [2]:
# NumPy
m_np = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
v_np = np.array([10, 20, 30])            # shape (3,)
print("NP 矩阵加行向量：\n", m_np + v_np) # v广播为[[10,20,30], [10,20,30]]

v_col_np = np.array([[10], [20]])        # shape (2, 1)
print("NP 矩阵加列向量：\n", m_np + v_col_np) # v_col广播为[[10,10,10], [20,20,20]]

# PyTorch
m_t = torch.tensor([[1, 2, 3], [4, 5, 6]])
v_t = torch.tensor([10, 20, 30])
print("Torch 矩阵加行向量：\n", m_t + v_t)
v_col_t = torch.tensor([[10], [20]])
print("Torch 矩阵加列向量：\n", m_t + v_col_t)


NP 矩阵加行向量：
 [[11 22 33]
 [14 25 36]]
NP 矩阵加列向量：
 [[11 12 13]
 [24 25 26]]
Torch 矩阵加行向量：
 tensor([[11, 22, 33],
        [14, 25, 36]])
Torch 矩阵加列向量：
 tensor([[11, 12, 13],
        [24, 25, 26]])


In [3]:
# NumPy
a_np = np.array([[1], [2], [3]])      # shape (3, 1)
b_np = np.array([[10, 20, 30, 40]])   # shape (1, 4)
print("NP (3,1) + (1,4)：\n", a_np + b_np) # 结果shape (3, 4)

# PyTorch
a_t = torch.tensor([[1], [2], [3]])
b_t = torch.tensor([[10, 20, 30, 40]])
print("Torch (3,1) + (1,4)：\n", a_t + b_t)


NP (3,1) + (1,4)：
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Torch (3,1) + (1,4)：
 tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


In [4]:
# NumPy: 模拟批量数据加偏置
batch_data_np = np.random.randn(32, 10)  # 32个样本，每个10维特征，shape (32, 10)
bias_np = np.ones(10)                    # 10维偏置， shape (10,)
output_np = batch_data_np + bias_np      # bias广播为(32, 10)
print("NP 批量广播后形状：", output_np.shape) # (32, 10)

# PyTorch
batch_data_t = torch.randn(32, 10)
bias_t = torch.ones(10)
output_t = batch_data_t + bias_t
print("Torch 批量广播后形状：", output_t.shape)


NP 批量广播后形状： (32, 10)
Torch 批量广播后形状： torch.Size([32, 10])


In [5]:
# NumPy
try:
    a_err = np.array([[1, 2], [3, 4]])  # (2, 2)
    b_err = np.array([1, 2, 3])         # (3,)
    print(a_err + b_err)
except ValueError as e:
    print(f"NP 错误案例: {e}") # 最后一个维度 2 != 3 且都不为1

# PyTorch
try:
    a_err_t = torch.tensor([[1, 2], [3, 4]])
    b_err_t = torch.tensor([1, 2, 3])
    print(a_err_t + b_err_t)
except RuntimeError as e:
    print(f"Torch 错误案例: {e}")


NP 错误案例: operands could not be broadcast together with shapes (2,2) (3,) 
Torch 错误案例: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


In [6]:
# NumPy 使用np.newaxis增加维度
a_np = np.array([1, 2, 3])  # (3,)
a_row = a_np[np.newaxis, :] # 变为行向量 (1, 3)
a_col = a_np[:, np.newaxis] # 变为列向量 (3, 1)
print("NP newaxis 行向量形状：", a_row.shape)
print("NP newaxis 列向量形状：", a_col.shape)

# PyTorch 使用view或unsqueeze
a_t = torch.tensor([1, 2, 3])
a_row_t = a_t.unsqueeze(0)  # 在0维增加维度， (1, 3)
a_col_t = a_t.unsqueeze(1)  # 在1维增加维度， (3, 1)
print("Torch unsqueeze 行向量形状：", a_row_t.shape)
print("Torch unsqueeze 列向量形状：", a_col_t.shape)


NP newaxis 行向量形状： (1, 3)
NP newaxis 列向量形状： (3, 1)
Torch unsqueeze 行向量形状： torch.Size([1, 3])
Torch unsqueeze 列向量形状： torch.Size([3, 1])
